stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./python/Dockerfile
      buildContext: ./python/
      tag: python:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy_python/deployment.yml
timeout: 60
notification: {}
