stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./python/Dockerfile
      buildContext: ./python/
      tag: python:${CICD_EXECUTION_SEQUENCE}
  #    registry: 127.0.0.1:34623
  #  env:
  #    PLUGIN_DEBUG: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deploy_python/deployment.yml
timeout: 60
notification: {}
