stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./httpd/Dockerfile
      buildContext: ./httpd/
      tag: httpd:${CICD_EXECUTION_SEQUENCE}
  #    registry: 127.0.0.1:34623
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment/service-httpd.yml
  - applyYamlConfig:
      path: ./deployment/deploy-httpd.yml
timeout: 60
notification: {}
