apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  # namespace: cicd
  labels:
    app: sitti
    tier: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitti
      tier: httpd
  template:
    metadata:
      labels:
        app: sitti
        tier: httpd
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: httpd
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
          name: http
