apiVersion: v1
kind: Service
metadata:
  namespace: ci-cd
  name: httpd
  labels:
    app: sitti
    tier: httpd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31234
    protocol: TCP
    name: http


  selector:
    tier: httpd

