apiVersion: v1
kind: Service
metadata:
  # namespace: cicd
  name: httpd
  labels:
    app: sitti
    tier: httpd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http


  selector:
    tier: httpd

